### ISSUE TITLE
IntegrationFlowDefinition#registerOutputChannelIfCan should rely on interfaces rather than abstract implementations

### ISSUE THREAD

**Issue by pfijalki** [spring-projects/spring-integration-java-dsl#140] opened 2017-01-29 16:30 UTC
is:

```Java
// line 3031
if (currentComponent instanceof AbstractMessageProducingHandler) {
					AbstractMessageProducingHandler messageProducer =
							(AbstractMessageProducingHandler) currentComponent;
					checkReuse(messageProducer);
					if (channelName != null) {
						messageProducer.setOutputChannelName(channelName);
					}
					else {
						messageProducer.setOutputChannel(outputChannel);
					}
				}
```

should be:

```Java
if ( outputChannel != null && currentComponent instanceof MessageProducer) {
					final MessageProducer messageProducer =
							(MessageProducer) currentComponent;
					 checkReuse(messageProducer);
						messageProducer.setOutputChannel(outputChannel);
					
} else if (channelName != null && currentComponent instanceof AbstractMessageProducingHandler){

              final AbstractMessageProducingHandler messageProducingHandler =  (AbstractMessageProducingHandler) currentComponent;

	     checkReuse(messageProducingHandler);
messageProducingHandler.setOutputChannelName(channelName);

}
```

**Comment by artembilan** [comment] 2017-01-29 17:03
Would you mind to share the reason what made you to contact with us?

**Comment by pfijalki** [comment] 2017-01-29 17:07
Hi @artembilan. Sure -  I was trying to test/implement integration flow and found these lines, are my reasons important for this issue ?

**Comment by artembilan** [comment] 2017-01-29 17:11
M-m-m, sorry, not sure how that proves that we have a problem.

**Comment by pfijalki** [comment] 2017-01-29 17:21
check out this setup. Why this dsl forbids creation of such flows ? What responsibility carries AbstractMessageHandler that is required by this setup ?

Handler def:
```Java
  interface MessageProducingHandler extends MessageHandler, MessageProducer {

  }
```

Flow setup:

```Java
  @Bean
  IntegrationFlow integrationFlow() {

    return flow ->
        flow.channel("input")
            .handle(handler())
            .channel("output");
  }
```

Handler impl:
```Java
  @Bean
  MessageProducingHandler handler() {

    return new MessageProducingHandler() {

      private MessageChannel outputChannel;

      @Override
      public void setOutputChannel(final MessageChannel outputChannel) {

        this.outputChannel = outputChannel;
      }

      @Override
      public MessageChannel getOutputChannel() {

        return this.outputChannel;
      }

      @Override
      public void handleMessage(final Message<?> message) throws MessagingException {
        // handle here
        this.getOutputChannel().send(message);
      }
    };
  }
```

Exception caught:

```
Caused by: org.springframework.beans.factory.BeanCreationException: The 'currentComponent' (com.project.FlowConfiguration$1@4d6ee47) is a one-way 'MessageHandler' and it isn't appropriate to configure 'outputChannel'. This is the end of the integration flow.
	at org.springframework.integration.dsl.IntegrationFlowDefinition.registerOutputChannelIfCan(IntegrationFlowDefinition.java:3053)
	at org.springframework.integration.dsl.IntegrationFlowDefinition.channel(IntegrationFlowDefinition.java:227)
```

**Comment by pfijalki** [comment] 2017-01-29 19:47
@artembilan ok, now I get It. because of 

```Java
	public void setOutputChannelName(String outputChannelName) {
		Assert.hasText(outputChannelName, "'outputChannelName' must not be empty");
		this.outputChannelName = outputChannelName; //NOSONAR (inconsistent sync)
	}
```

nevertheless maybe there's a way to fix this design flaw in spring integration ?

**Comment by garyrussell** [comment] 2017-01-29 21:12
The problem is that the `AbstractMessageProducingHandler` provides much goodness - resolving channel names to channels, handling splittable output, handling the routing slip header; handling async replies (`ListenableFuture`), including the handling of downstream errors; properly dealing with the reply channel and error channel headers; propagating headers from the input to output message, etc, etc.

Because of all this goodness, we generally recommend extending the framework abstract classes rather than implementing your own `MessageHandler` completely from scratch.

**Comment by pfijalki** [comment] 2017-01-30 08:56
@garyrussell agreed about those goodness - whether designing it in this abstract class was a good desicision is a orthogonal matter. Wrapping this all discussion up, my point here is that

- for this particular function (setting output channel by reference) nothing more than MessageProducer is necessary and this should be target object of the cast. It would be nice to keep this interface separation here

**Comment by artembilan** [comment] 2017-01-30 17:13
While we really recommend to try to reuse Framework abstractions for target applications as much as possible it doesn't mean that we really should prohibit to build the application own logic as that fits to the business requirements or end-developer sanity.

We definitely can switch there to just `MessageProducer` for `MessageChannel` case. And try to come up with the `AbstractMessageProducingHandler` when we expect `setOutputChannelName()`.

But since this issue doesn't have practical requirements (IMHO) I only consider fixing it in the the current Spring Integration `master` for version `5.0`. No reason to backport this small design flaw if it can be addressed with a proper workaround via  `AbstractMessageProducingHandler` extension.

**Closed** 2017-01-30 19:00 UTC

**Comment by pfijalki** [comment] 2017-01-30 19:28
Cool! Thanks @artembilan, @garyrussell :+1:
