### ISSUE TITLE
DefaultMessageListenerContainer not shutting down properly on Tomcat Manager stop/undeploy

### ISSUE THREAD

**Issue by jltnf54** [spring-projects/spring-integration-java-dsl#95] opened 2016-07-17 16:16 UTC
DefaultMessageListenerContainer seems to hang on Tomcat Manager stop/undeploy.  SimpleAsyncTaskExecutor does not appear to shutdown properly.

**Comment by jltnf54** [comment] 2016-07-17 16:23
Example setup:

IntegrationFlows.from(Jms.messageDrivenChannelAdapter(connectionFactory)
				.id("MyAdapter")
				.destination(destination)
				.autoStartup(true)
				.configureListenerContainer(c -> {
					c.durableSubscriptionName("MyTopic");
					c.sessionAcknowledgeMode(0);
					c.destinationResolver(destinationResolver);
				c.subscriptionDurable(jmsMessagingProperties.isJmsSubscriptionDurable());
					c.sessionTransacted(true);
					c.acceptMessagesWhileStopping(false);
					c.pubSubDomain(true);
//					c.get().setTaskExecutor(jmsAsyncExecutor);
//					c.get().setBeanName("MyMessageListenerContainer");
				})

Shutdown if you provide custom executor:

...
	@Bean(destroyMethod = "destroy")
	public TaskExecutorFactoryBean jmsAsyncExecutor() {
		final TaskExecutorFactoryBean result = new TaskExecutorFactoryBean();
		result.setQueueCapacity(Integer.MAX_VALUE);
		result.setPoolSize("20-25");
		return result;
	}

	@Autowired
	@Qualifier("jmsAsyncExecutor")
	TaskExecutor jmsAsyncExecutor;

IntegrationFlows.from(Jms.messageDrivenChannelAdapter(connectionFactory)
				.id("MyAdapter")
				.destination(destination)
				.autoStartup(true)
				.configureListenerContainer(c -> {
					c.durableSubscriptionName("MyTopic");
					c.sessionAcknowledgeMode(0);
					c.destinationResolver(destinationResolver);
				c.subscriptionDurable(jmsMessagingProperties.isJmsSubscriptionDurable());
					c.sessionTransacted(true);
					c.acceptMessagesWhileStopping(false);
					c.pubSubDomain(true);
					c.get().setTaskExecutor(jmsAsyncExecutor);
//					c.get().setBeanName("MyMessageListenerContainer");
				})

**Comment by jltnf54** [comment] 2016-07-17 16:24
did mean to close issue

**Comment by jltnf54** [comment] 2016-07-17 16:29
Example code for JmsMessageDrivenChannelAdapter:
`	protected IntegrationFlowBuilder messageDrivenChannelAdapterFlowTemplate(ConnectionFactory connectionFactory,
			String topicKey, Destination destination) {
		return IntegrationFlows.from(Jms.messageDrivenChannelAdapter(connectionFactory)
				.id(String.format("%sMessageChannelAdapter", topicKey))
				.destination(destination)
				.autoStartup(true)
				.configureListenerContainer(c -> {
					c.durableSubscriptionName(topicKey);
					c.sessionAcknowledgeMode(0);
					c.destinationResolver(destinationResolver);
					c.subscriptionDurable(jmsMessagingProperties.isJmsSubscriptionDurable());
					c.sessionTransacted(true);
					c.acceptMessagesWhileStopping(false);
					c.pubSubDomain(true);
				})
				.errorChannel(customErrorChannel()))
				.handle(jmsInboundConsumer);
	}`

Changing executor seems to work, but does not seem right to do.

`	@Bean(destroyMethod = "destroy")
	public TaskExecutorFactoryBean jmsAsyncExecutor() {
		final TaskExecutorFactoryBean result = new TaskExecutorFactoryBean();
		result.setQueueCapacity(Integer.MAX_VALUE);
		result.setPoolSize("20-25");
		return result;
	}

	@Autowired
	@Qualifier("jmsAsyncExecutor")
	TaskExecutor jmsAsyncExecutor;

	protected IntegrationFlowBuilder messageDrivenChannelAdapterFlowTemplate(ConnectionFactory connectionFactory,
			String topicKey, Destination destination) {
		return IntegrationFlows.from(Jms.messageDrivenChannelAdapter(connectionFactory)
				.id(String.format("%sMessageChannelAdapter", topicKey))
				.destination(destination)
				.autoStartup(true)
				.configureListenerContainer(c -> {
					c.durableSubscriptionName(topicKey);
					c.sessionAcknowledgeMode(0);
					c.destinationResolver(destinationResolver);
					c.subscriptionDurable(jmsMessagingProperties.isJmsSubscriptionDurable());
					c.sessionTransacted(true);
					c.acceptMessagesWhileStopping(false);
					c.pubSubDomain(true);
					c.get().setTaskExecutor(jmsAsyncExecutor);
//					c.get().setBeanName(topicKey + "MessageListenerContainer");
				})
				.errorChannel(customErrorChannel()))
				.handle(jmsInboundConsumer);
	}`

**Comment by artembilan** [comment] 2016-07-18 14:29
> Changing executor seems to work, but does not seem right to do.

Actually that is only correct way to go, if your application is controlled by the EE container.
The problem is in exactly `DefaultMessageListenerContainer` and there is nothing how Spring Integration Java DSL affect that. 
See `DefaultMessageListenerContainer` JavaDocs:
```
/**
 * Set the Spring {@code TaskExecutor} to use for running the listener threads.
 * <p>Default is a {@link org.springframework.core.task.SimpleAsyncTaskExecutor},
 * starting up a number of new threads, according to the specified number
 * of concurrent consumers.
 * <p>Specify an alternative {@code TaskExecutor} for integration with an existing
 * thread pool. Note that this really only adds value if the threads are
 * managed in a specific fashion, for example within a Java EE environment.
 * A plain thread pool does not add much value, as this listener container
 * will occupy a number of threads for its entire lifetime.
 * @see #setConcurrentConsumers
 * @see org.springframework.core.task.SimpleAsyncTaskExecutor
 * @see org.springframework.scheduling.commonj.WorkManagerTaskExecutor
 */
public void setTaskExecutor(Executor taskExecutor) {
	this.taskExecutor = taskExecutor;
}
```

Closing as "Works as Designed".

Feel free reopen but in the proper project the next time.
Particularly this one is for [Spring Framework](https://jira.spring.io/browse/SPR).

**Comment by jltnf54** [comment] 2016-07-20 04:07
ok thanks, i have done that according to javadoc. However but should the dsl allow you to specify the exectors, instead of call .get()

**Comment by artembilan** [comment] 2016-07-20 14:21
> However but should the dsl allow you to specify the exectors, instead of call .get()

I don't understand your question. 

The `taskExecutor` is a property of `DefaultMessageListenerContainer`.
The Java DSL allows you to inject such a bean into `Jms.messageDriverChannelAdapter()` definition.

There is, of course, other trick like:
```
IntegrationFlows
	.from(Jms.messageDrivenChannelAdapter(this.jmsConnectionFactory)
		.outputChannel(jmsMessageDriverInputChannel())
		.destination("jmsMessageDriver")
		.configureListenerContainer(c -> {
				DefaultMessageListenerContainer container = c.get();
				container.setTaskExecutor(taskExecutor());
			}))
```
Although, it seems for me, I see your point and there might be better to expose all those `DefaultMessageListenerContainer` properties into `JmsListenerContainerSpec` avoid that `.get()`.

For example as a `DefaultMessageListenerContainerSpec extends JmsListenerContainerSpec<DefaultMessageListenerContainer>`.

WDYT?

**Comment by jltnf54** [comment] 2016-07-20 15:46
sorry for the confusion. Yes, if possible can the dsl library expose the additional properties. 

example:
`IntegrationFlows.from(Jms.messageDrivenChannelAdapter(this.jmsConnectionFactory)
         .outputChannel(jmsMessageDriverInputChannel())
         .destination("jmsMessageDriver")
         .configureListenerContainer(c -> {
                c.executor(taskExecutor());
}))`

**Closed** 2016-07-25 14:18 UTC
Labels: enhancement
