### ISSUE TITLE
IntegrationFlowBeanPostProcessor.afterSingletonsInstantiated

### ISSUE THREAD

**Issue by cigaly** [spring-projects/spring-integration-java-dsl#120] opened 2016-09-21 10:10 UTC
In following code from `afterSingletonsInstantiated` `BeanCreationNotAllowedException` will be thrown if bean factory contains ANY non-singleton bean, even if it is not connected with any integration flow. Is that intentional or just an undocumented feature?
````java
for (String beanName : this.beanFactory.getBeanDefinitionNames()) {
    if (this.beanFactory.containsBeanDefinition(beanName)) {
        String scope = this.beanFactory.getBeanDefinition(beanName).getScope();
        if (StringUtils.hasText(scope) && !BeanDefinition.SCOPE_SINGLETON.equals(scope)) {
            throw new BeanCreationNotAllowedException(beanName, "IntegrationFlows can not be scoped beans. " +
                    "Any dependant beans are registered as singletons, meanwhile IntegrationFlow is just a " +
                    "logical container for them. \n" +
                    "Consider to use [IntegrationFlowContext] for manual registration of IntegrationFlows.");
        }
    }
}
````

**Comment by artembilan** [comment] 2016-09-21 12:25
Oh! That's really a big bug.
I'm implied the limitation only for the `IntegrationFlow` beans, but the code really doesn't care about that and just disable any `scope` :cry: 

Will be fixed today.

Thank you for catching that!

**Comment by cigaly** [comment] 2016-09-21 14:25
I'm not quite sure, but probably it could help to add outer loop like:

for (String integrationFlowBeanName : BeanFactoryUtils.beanNamesForTypeIncludingAncestors(beanFactory, IntegrationFlow.class))

and then in inner loop:

for (String beanName : beanFactory.getDependenciesForBean(integrationFlowBeanName))

?

**Comment by artembilan** [comment] 2016-09-21 14:32
Yep! Thank you for considering the fix.

No, we don't need any dependent beans. Only concern that `IntegrationFlow` can't be in scope. 

The problem is here: https://github.com/spring-projects/spring-integration-java-dsl/pull/110/commits/4bd49bde607b3045b306a0668152d4e829c3d5e2#r77204013. If the bean is in scope we will know that only after calling that bean. 
So, for fail fast I decided to switch to the `afterSingletonsInstantiated()`. But yeah... that was really an oversight do not filter beans only for the `IntegrationFlow`.

The `beanNamesForType()` would be a great solution though.
Thank you for pointing that out!

Maybe you wouldn't mind of the [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc)?

**Comment by cigaly** [comment] 2016-09-21 14:40
My mistake ... I've misunderstood exception message. In that case, I believe that only one loop will solve all problems:

for (String beanName : BeanFactoryUtils.beanNamesForTypeIncludingAncestors(beanFactory, IntegrationFlow.class))

**Comment by artembilan** [comment] 2016-09-21 14:44
Something like that.

Please, don't hesitate to provide a Pull Request and we'll continue a discussion there on lines.

**Closed** 2016-09-21 19:40 UTC
Labels: bug
